mckinseyacademy/mcka-theme

lms/static/sass/discussion/lms-discussion-main.scss

- Fixed body & Footer links color caused by lms-discussion-main.scss

Discussion page styles overrides

---

lms/static/sass/xblocks/image_explorer.scss

- Added theme for hotspot right pane in IEv2
Ticket: [https://edx-wiki.atlassian.net/browse/MCKIN-7571](https://edx-wiki.atlassian.net/browse/MCKIN-7571)
@kaizoku Please review and merge 
CC: @xitij2000

MCKIN-7571 IE2 Hotspot detail pane theme

---

lms/static/sass/xblocks/image_explorer.scss

Reverts mckinseyacademy/mcka-theme#16
@kaizoku We are merging our new theme changes in master branch but we are not using latest DnDv4 and IEv2. It has created an issue on development server [(See this issue)](https://edx-wiki.atlassian.net/browse/MCKIN-8248). i-e the IEv2 theme changes have applied to IEv1. So i am creating this PR to revert our previous PR please revert it ASAP and we should create two branches: one for DnDv4 and one for IEv2 so we can merge our new theme changes in them. 
CC: @xitij2000 @bradenmacdonald

Revert "MCKIN-7571 IE2 Hotspot detail pane theme"

---

lms/static/sass/xblocks/drag_and_drop.scss

Thanks @xitij2000 I have creted this PR to revert the previous changes that should be in a temp branch. I will create temp branches i-e drag-and-drop-v4 & image-explorer-v2 for all the new theme changes. 
Please merge this PR

Revert MCKIN-7741 changes from Master branch

---

lms/static/sass/xblocks/problem_builder.scss

Applies theme fixes restore the previous styling after changes to problem builder in https://github.com/open-craft/problem-builder/pull/203.

[MCKIN-8242] Theme fixes for problem-builder

---

lms/static/sass/base/_variables.scss
lms/static/sass/xblocks/drag_and_drop.scss

- Styling for new item bank slider 
Ticket: [https://edx-wiki.atlassian.net/browse/MCKIN-7741](https://edx-wiki.atlassian.net/browse/MCKIN-7741)
@xitij2000 @viadanna  @kaizoku Please review and merge
P.S: This work was merged in master branch previously but had to revert as all the temporary changes should go to "IE2-and-DnD4" branch
ref: [https://github.com/mckinseyacademy/mcka-theme/pull/20](https://github.com/mckinseyacademy/mcka-theme/pull/20)

MCKIN-7741 item bank styling

---

lms/static/sass/base/_variables.scss
lms/static/sass/xblocks/drag_and_drop.scss

- Added theme for wrong and right poup
Tikects: 
[https://edx-wiki.atlassian.net/browse/MCKIN-7636](https://edx-wiki.atlassian.net/browse/MCKIN-7636)
[https://edx-wiki.atlassian.net/browse/MCKIN-7638](https://edx-wiki.atlassian.net/browse/MCKIN-7638)
@kaizoku Please review and merge
CC: @bradenmacdonald  @xitij2000

MCKIN-7636 & MCKIN-7638 Theme for right and wrong popup for V4

---

lms/static/sass/base/_variables.scss
lms/static/sass/xblocks/drag_and_drop.scss

- Added buttons for standard mode
**Ticket:**
[https://edx-wiki.atlassian.net/browse/MCKIN-8237](https://edx-wiki.atlassian.net/browse/MCKIN-8237)
**Change to verify:**
@viadanna Please review and merge

MCKIN-8237 & MCKIN-8238 Buttons bar standard mode

---

lms/static/sass/base/_variables.scss
lms/static/sass/xblocks/drag_and_drop.scss

- Window notification for assessment mode
**Ticket:**
[https://edx-wiki.atlassian.net/browse/MCKIN-8026](https://edx-wiki.atlassian.net/browse/MCKIN-8026)
@viadanna Please review and merge

MCKIN-8026 Assessment window Notification

---

lms/static/sass/_overrides.scss

Adding remaining xblocks styling for mobile.
Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-8974

MCKIN-8974-fixed-for-mobile

---

lms/static/sass/_overrides.scss

MCKIN-8974-fixed-for-mobile (#30)

---

lms/static/sass/_overrides.scss
lms/static/sass/lms-main-v1-rtl.scss
lms/static/sass/lms-main-v2-rtl.scss
lms/static/sass/xblocks/chat.scss

- Added rtl versions of lms-main.css i-e lms-main-v1-rtl &  lms-main-v2-rtl
**Ticket:**
[https://edx-wiki.atlassian.net/browse/MCKIN-9127](https://edx-wiki.atlassian.net/browse/MCKIN-9127)

MCKIN-9127 Adding rtl version of lms-main.css

---

lms/static/sass/xblocks/problem_builder.scss

issue solved by adding custom css in the theme for problem-builder xblock

issue solved by adding custom css

---

lms/static/sass/xblocks/common.scss

The last [PR ](https://github.com/mckinseyacademy/mcka-theme/pull/45) caused issues on new and old new. I have reverted the css property that was causing issue.
@xitij2000 Please review it so that I can merge it

Revert row width

---

lms/static/sass/xblocks/problem_builder.scss

Problembuilder changes

---

lms/static/sass/xblocks/common/_buttons.scss
lms/static/sass/xblocks/form/_checkbox.scss
lms/static/sass/xblocks/form/_radiobutton.scss
lms/static/sass/xblocks/problem_builder.scss

radio button and checkboxes fix for old UI

radio button and checkboxes fix for old UI

---

lms/static/sass/apros-xblocks.scss
lms/static/sass/xblocks/core/_core.scss
lms/static/sass/xblocks/scorm.scss
lms/static/sass/xblocks/vars/_variables.scss

Ensure SCORM is responsive and usable in a web browser on all devices and applies New UI styles

Scorm xBlock - 9105

---

lms/static/sass/xblocks/problem_builder.scss

fixed the icons for checkbox and radio buttons incorrect and correct icons.

fixed the correct/incorrect icons for radio/checkboxes

---

lms/static/sass/apros-xblocks.scss
lms/static/sass/xblocks/simulated-chat.scss
lms/static/sass/xblocks/vars/_variables.scss

add the styling for Simulated Chat xBlock.

Simulated-Chat-9425

---

lms/static/sass/apros-xblocks.scss
lms/static/sass/base/_buttons.scss
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss
lms/static/sass/xblocks/form/_checkbox.scss
lms/static/sass/xblocks/form/_radiobutton.scss

@murad-hubib I understand inline discussion can be imported in inline-discussion rather in apros. But it was not working at my end. Anyway its a one liner change so we can do those changes.

Prakash/mckin 9108 - Discussion -inline xblock

---

lms/static/js/apros-xblocks.js
lms/static/sass/base/_buttons.scss
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/xblocks/ooyala_videos.scss
lms/static/sass/xblocks/poll_survey.scss

edit button in discussion
show hide discussion toggler
chat bubble height
video player centre play button
poll-survey bugs

mckin 10310 + post demo feedback changes

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/xblocks/image_explorer.scss
lms/static/sass/xblocks/problem_builder.scss

inline button placements changed as per recommendations. Image explorer mobile's popup center always. Free text replay will width enabled.

Post demo suggestions

---

lms/static/sass/xblocks/problem_builder.scss

fixed the issue of problem builder-radio button and RTL

fixed the issue of problem builder-radio button and RTL

---

lms/static/sass/discussion/inline-discussion.scss

#5 - please remove code sample and image upload for now.
#6 - "Y" is cutting for "Post Anonymously"
#7 - In current we can click anywhere for respective discussion area but in NEW UI we have to move the cursor on the title or on discussion icon
#8 - For the 2nd and coming next comments on a post when we click on "more" button the Edit/Delete button is disturbed this happens also for the TA user
#9 - Trying to make hyprelink but the appearing design box is not responsive
#11 - When we login TA user and opens up the discussions then there is some overlapping
#12 - When we hover on Cancel the box hides

MCKIN-10441

---

lms/static/sass/xblocks/assessment.scss
lms/static/sass/xblocks/problem_builder.scss

Assessment fixes

---

lms/static/sass/xblocks/problem_builder.scss

fix feedback box on rtl

---

lms/static/sass/xblocks/simulated-chat.scss

fixed the changes of the Chat xblock.

fixed the chat issues.

---

lms/static/sass/xblocks/diagnostic.scss

Fixes issues for Diagnostic feedback xBlock

MCKIN-10324 Diagnostic feedback 

---

lms/static/sass/discussion/lms-discussion-main.scss

@murad-hubib @shahidrafique @furqan-ud-din  please review and merge

Layout issues on learner dashboard

---

lms/static/sass/xblocks/common/_buttons.scss
lms/static/sass/xblocks/scorm.scss

MCKIN-10467 fix the button style issue for Scorm UI

MCKIN-10467 fix the button style issue for Scorm UI

---

lms/static/js/apros-xblocks.js
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss
lms/static/sass/discussion/partials/_discussion-mobile-forum-content.scss
lms/static/sass/xblocks/form/_radiobutton.scss
lms/static/sass/xblocks/poll_survey.scss

Username should not be clickable - fixed
Tool bar above response text box is cutting off from right side in mobile portrait mode - We don't have Toolbar in mobiles in current UI so removed same from new UI.
extra space between this post is visible to everyone and add a response heading in Mobile -Fixed
Survey
when private result is true - radio button selected and disabled

mckin 10503 10527 except ie bugs 

---

lms/static/sass/xblocks/simulated-chat.scss

changed the style of selected reply button in Chat Xblock

MCKIN-10326 changed the style of selected reply button in Chat Xblock

---

lms/static/sass/base/_buttons.scss
lms/static/sass/base/_variables.scss
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss
lms/static/sass/xblocks/common.scss
lms/static/sass/xblocks/common/_buttons.scss
lms/static/sass/xblocks/drag_and_drop.scss
lms/static/sass/xblocks/image_explorer.scss
lms/static/sass/xblocks/poll_survey.scss
lms/static/sass/xblocks/problem_builder.scss
lms/static/sass/xblocks/vars/_variables.scss

on IE var doesn't work so have added a fallback color - so it wil beblue theme whenever var is not readable by unsupported browsers.

Fallback colour added for IE.

---

lms/static/sass/apros-xblocks.scss
lms/static/sass/xblocks/html_module.scss

[Major] [RTL] [ios] - First letter is Cutting of the screen issue fixed.

MCKIN-10437 fixed First letter is Cutting of the screen in html module

---

lms/static/sass/xblocks/poll_survey.scss

MCKIN-10570 -  Make Poll and Survey compatible for RTL

MCKIN-10570 - Poll and Survey styling for RTL

---

lms/static/sass/xblocks/assessment.scss
lms/static/sass/xblocks/drag_and_drop.scss
lms/static/sass/xblocks/problem_builder.scss

Replace the x icon with ! in 3 xBlocks, Problem builder, Assessment and Drag&Drop.

MCKIN-10603 - update x icon

---

lms/static/sass/xblocks/problem_builder.scss

MCKIN-10566 - FTR RTL Styling

---

lms/static/sass/xblocks/poll_survey.scss

MCKIN-10570-RTL-Poll-Survey

---

lms/static/sass/base/_buttons.scss
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss
lms/static/sass/xblocks/common.scss
lms/static/sass/xblocks/drag_and_drop.scss

hidden text could be selected + other fixes

hidden content could be selected + other fixes

---

lms/static/sass/base/_buttons.scss
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss
lms/static/sass/xblocks/drag_and_drop.scss
lms/static/sass/xblocks/image_explorer.scss

@murad-hubib @shahidrafique @furqan-ud-din please review and merge

sprint 6 fixes 2

---

lms/static/sass/xblocks/adventure.scss
lms/static/sass/xblocks/diagnostic.scss

fixed the issues of adventure.

MCKIN-10362 fixed the issue of adventure

---

lms/static/sass/base/_buttons.scss
lms/static/sass/base/_variables.scss
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss
lms/static/sass/xblocks/common/_buttons.scss
lms/static/sass/xblocks/drag_and_drop.scss
lms/static/sass/xblocks/ooyala_videos.scss
lms/static/sass/xblocks/vars/_variables.scss

@shahidrafique please review and merge

new branding updates

---

lms/static/sass/xblocks/poll_survey.scss

Fixed the RTL and Mobile issue.

Mckin 10570 rtl poll survey

---

lms/static/sass/xblocks/image_explorer.scss

@shahidrafique  please review and merge

RTL for image explorer & icons branding

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/xblocks/image_explorer.scss

@furqan-ud-din @shahidrafique please review and merge

MCKIN-10810

---

lms/static/js/apros-xblocks.js

adding disabled effect on polls
@shahidrafique please review and merge

MCKIN-10742

---

lms/static/js/apros-xblocks.js
lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss

@shahidrafique @furqan-ud-din @murad-hubib  please review and merge

when polls are private- MCKIN-10742

---

lms/static/sass/discussion/lms-discussion-main.scss

@murad-hubib or @hussnain2 anyone of you please

MCKIN-10889-fixed the width of the search field for all posts.

---

lms/static/sass/xblocks/drag_and_drop.scss

MCKIN-10977 - fixed the hover state and width of the buttons in mobile device.

MCKIN-10977 - fixed the hover state and width of the buttons in mobile device.

---

lms/static/sass/xblocks/drag_and_drop.scss

Fixed the issue of Drag and Drop, image get reduce when it viewed at mobile device.

MCKIN-11028 fixed the image width and height issue in mobile.

---

lms/static/sass/xblocks/ooyala_videos.scss

- Fixed ui issues for updated ooyala player
- Removed background of "1x" and "CC" buttons
- Removed duplicate pause and play icons and their shadows
**Ticket:**
[https://edx-wiki.atlassian.net/browse/MCKIN-11120](https://edx-wiki.atlassian.net/browse/MCKIN-11120)

MCKIN-11120 Ooyala payer UI fixes

---

lms/static/sass/discussion/lms-discussion-main.scss

- Fixed icon colors from blue to primary color when seeing posts user is following

MCKIN-11157 Fixed icon colors

---

lms/static/sass/discussion/lms-discussion-main.scss

- Fixed hover color of links in "Posts i am following" section

MCKIN-11157 Added hover color for links

---

lms/static/sass/xblocks/image_explorer.scss

- Fixed overlapping bullets of list in hotspot popups

MCKIN-10679 IE - popup list bullets fix

---

lms/static/sass/xblocks/image_explorer.scss

Fixed default bullets in font awesome list

MCKIN-10679 IE list double bullets

---

lms/static/sass/xblocks/poll_survey.scss
lms/static/sass/xblocks/problem_builder.scss

@shahidrafique please verify these changes to run this code at your local, before approving this PR.

MCKIN-11440 checkbox alignments

---

lms/static/sass/xblocks/poll_survey.scss

@shahidrafique It's nice to have if you run these changes at your local environment.

Mckin 11440 v3

---

lms/static/js/apros-xblocks.js

prevent scroll on body when DnD item is being dragged

MCKIN-11622: prevent scroll on body when DnD item is being dragged

---

lms/static/js/apros-xblocks.js

Reverts mckinseyacademy/mcka-theme#196

Revert "MCKIN-11622: prevent scroll on body when DnD item is being dragged"

---

lms/static/js/apros-xblocks.js

Reverts mckinseyacademy/mcka-theme#199

Revert "Revert "MCKIN-11622: prevent scroll on body when DnD item is being dragged""

---

lms/static/sass/discussion/inline-discussion.scss

make a .sr element readable for Screen Reader.

---

lms/static/sass/xblocks/brightcov.scss

Fixed Closed captioning on Ooyala videos.

MCKIN-12589 ooyala rtl caption handling

---

lms/static/sass/xblocks/problem_builder.scss

- Added html x button and removed css properties as suggested by LevelAccess team
Ticket: 
https://edx-wiki.atlassian.net/browse/MCKIN-12189

MCKIN-12189 Feedback close button scss

---

lms/static/sass/discussion/lms-discussion-main.scss

Fixed the filter design that is disturbed for a TA user

MCKIN-11045 Filter design disturbed for TA user

---

lms/static/sass/xblocks/ooyala_videos.scss

Fixed z-index of multiple videos in full screen

MCKIN-11453 Z-index of multiple videos

---

lms/static/sass/xblocks/problem_builder.scss

- Overwrite the display property in theme to show the close button in problem builder feedback window

MCKIN-12189 Feedback window close button

---

lms/static/sass/xblocks/poll_survey.scss

Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-11212
Minor cosmetic nits.

MCKIN-11212 Survey feedback text formatting

---

lms/static/sass/xblocks/problem_builder.scss

- Fixed select direction in RTL for instructor tool for problem builder

MCKIN-11546 Instructor tool select direction in RTL

---

lms/static/sass/discussion/inline-discussion.scss

MCKIM-12338 | remove display:none property from styles

MCKIM-12338 | remove display:none property from styles

---

lms/static/sass/xblocks/ooyala_videos.scss

Reverts all commits for MCKIN-11453

Revert complete 11453

---

lms/static/sass/xblocks/problem_builder.scss

- Fixed default styles of replaced buttons for problem builder

MCKIN-12712 PB defult buttons overrides

---

lms/static/sass/discussion/lms-discussion-main.scss

- Removed content property of question type heading when creating new post in Discussion/inline Discussion

MCKIN-12235 Removed text from content property

---

lms/static/sass/xblocks/brightcov.scss

fixed the dropdown menu which was cutting from the right side

MCKIN-12723 - fixed the dropdown menu which was cutting from the right side

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss

Fixed the followings:
1. The lower border of the discussion box is missing on the web.
3. The heading "Visible to" is overlapping with the filter on mobile devices.

MCKIN-12688 UI issues on the main discussion board

---

lms/static/sass/xblocks/brightcov.scss

MCKIN-12726  add important to none property to hide the cc icon in the list

---

lms/static/js/apros-xblocks.js

We are merging this for now as we don't have any customized event for the required playback rate functionality. We would be updating this code later when we have a better solution for this functionality.
CC: @naeem91

MCKIN-12697 -  fixed the rate menu that wasnt working.

---

lms/static/sass/xblocks/image_explorer.scss

Reverts mckinseyacademy/mcka-theme#233
to test IE on QA

Revert "Mckin 12180 ie"

---

lms/static/sass/xblocks/image_explorer.scss

Reverts mckinseyacademy/mcka-theme#251

MCKIN-12180 Added back reverted code.

---

lms/static/sass/xblocks/problem_builder.scss

- Css for button tag after replacing div with button

MCKIN-12189 CSS for close button

---

lms/static/sass/xblocks/problem_builder.scss

- Changed css for problem builder feedback close button according to new markup

MCKIN-12189 Changes css for new markup

---

lms/static/sass/xblocks/common.scss
lms/static/sass/xblocks/drag_and_drop.scss

- Added focus of droppable regions of Drag & Drop 
- Displayed keyboard help button

MCKIN-12219 Focus and display of DND help button

---

lms/static/sass/xblocks/common.scss
lms/static/sass/xblocks/drag_and_drop.scss

MCKIN-12219 Zone focus hotfix

---

lms/static/sass/xblocks/problem_builder.scss

- Override default buttons scss for newly replaced buttons with actual tags

MCKIN-12712 button scss overrides

---

lms/static/sass/xblocks/image_explorer.scss

- MCKIN-12760 fix white background issue

MCKIN-12760 background fix

---

lms/static/js/apros-xblocks.js

Reverting playback rate dropdown to toggle.

MCKIN-12697 reverting dropdown to toggle

---

lms/static/js/apros-xblocks.js

Fixed closed caption scrolling

MCKIN-12633 fix scrolling

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss

MCKIN-11615 fixing ie ui issues and buttons hover background

MCKIN-11615-IE UI FIXS

---

lms/static/sass/xblocks/drag_and_drop.scss
lms/static/sass/xblocks/simulated-chat.scss

MCKIN-12806-FIX button bg issue on hover

MCKIN-12806-FIX button bg issue on hover

---

lms/static/sass/xblocks/image_explorer.scss

MCKIN-12760-FIXING

---

lms/static/sass/xblocks/simulated-chat.scss

MCKIN-12806 FIXING

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss

MCKIN-11615-fixing

---

lms/static/sass/xblocks/image_explorer.scss

MCKIN-12760 ICON FIXING

---

lms/static/sass/xblocks/brightcov.scss

MCKIN-12878 video button focus remove

MCKIN-12878 video button focus remove

---

lms/static/sass/xblocks/assessment.scss
lms/static/sass/xblocks/problem_builder.scss

MCKIN-12770 | make changes for the messages sign and tool-tip on MCQ and MRQ's.

MCKIN-12770  | make changes for the messages sign and tool-tip on MCQ and MRQ's.

---

lms/static/sass/xblocks/image_explorer.scss

MCKIN-12760 IE hotspot container scroll issue

---

lms/static/sass/xblocks/image_explorer.scss

- Fixed SCSS structure according to new HTML structure

MCKIN-12760 Rearranged scss structre

---

lms/static/sass/xblocks/problem_builder.scss

MCKIN-12792-spaces-fix

---

lms/static/js/apros-xblocks.js

Inline-discussion header focus added via jquery as per level access recommendation

MCKIN-12809 Inline-discussion made accessible

---

lms/static/sass/xblocks/assessment.scss

MCKIN-12768 | icon alignment for the submit button area.

MCKIN-12768 | icon alignment for the cubmit.

---

lms/static/js/apros-xblocks.js

Discussion title header focus via jquery

MCKIN-12809 Discussion title header focus via jquery

---

lms/static/sass/xblocks/assessment.scss

MCKIN-12768 | make the element de-focused where, not needed.

Mckin 12768 assessment

---

lms/static/sass/discussion/inline-discussion.scss

Reverts mckinseyacademy/mcka-theme#236

Revert "MCKIM-12338 | remove display:none property from styles"

---

lms/static/sass/xblocks/problem_builder.scss

MCKIN-12981 | make changes for the MCQ | MRQ | assessment for RTL.

MCKIN-12981 | make changes for the MCQ | MRQ | assessment for RTL.

---

lms/static/sass/xblocks/assessment.scss

MCKIN-13021 | making the results align on mobile screens for Problem builder.

MCKIN-13021 | making the results align on mobile screens for Problem builder.

---

lms/static/js/apros-xblocks.js

MCKIN-12809 Discussion made accessible

---

lms/static/sass/xblocks/image_explorer.scss

- Fixed image explorer SCSS selectors for native app fixes

MCKIN-13004 Native app image-exp scss fix

---

lms/static/sass/base/_material_icons.scss

- Fixed fonts path for material icons

MCKIN-13004 fonts path fix

---

lms/static/sass/xblocks/brightcov.scss

- Removed new-theme class and fixed button shadows for brightcove video control bar

MCKIN-13229 native ie video btns

---

lms/static/sass/xblocks/problem_builder.scss

MCKIN-13278 feedback popup position and close button fix

MCKIN-13278 feedback popup position and close button fix

---

lms/static/sass/xblocks/chat.scss

- Fixed padding issues in chat for mobile apps

MCKIN-13266 Chat padding fixes for apps

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss

MCKIN-13489 fix text drop in next line

MCKIN-13489 fix text drop in next line

---

lms/static/sass/discussion/lms-discussion-main.scss

- Fixed width of discussion page on IE 11

MCKIN-13611 Discussion width on IE11

---

lms/static/sass/discussion/inline-discussion.scss

- Removed text from css content to fix RN app design

MCKIN-13656 Inline-D css text

---

lms/static/sass/discussion/inline-discussion.scss

- Fixed inline discussion, "Add a post" UI on mobile for RTL

MCKIN-13656 RTL for inline discussion

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-main.scss

- Fixed keyboard accessible radio buttons in "Add a post" section

MCKIN-14166  Discussion radio buttons keyboard accessible

---

lms/static/sass/discussion/lms-discussion-bootstrap.scss

- Updated file name of scss file for discussion

YONK-1596 Updated file name for Discussion

---

lms/static/sass/xblocks/drag_and_drop.scss

- Fixed drag and drop tiles touch and hold fix for chrome and RN app

MCKIN-13356 Chrome DND drag fix

---

lms/static/js/apros-xblocks.js
lms/static/sass/discussion/lms-discussion-bootstrap.scss

- fixed left discussion column and made it sticky when scrolling down the page

MCKIN-16947 Discussion left panel fix

---

lms/static/sass/discussion/lms-discussion-bootstrap.scss

Removed content which was coming from SASS

MCKIN-20612 string not translating in any language

---

lms/static/sass/discussion/inline-discussion.scss

- Fixed "add a post button on mobile"

MCKIN-21918 InlineD mobile button fix

---

lms/static/sass/discussion/inline-discussion.scss

- Fixed padding of "add a post" button on tap in mobile

MCKIN-21918 Hot fix

---

lms/static/sass/discussion/inline-discussion.scss

- Fixed buttons alignment on iphone for inline discussion buttons

MCKIN-21918 InlineD button iphone fix

---

lms/static/sass/xblocks/poll_survey.scss

Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-29154

MCKIN-29154 Polls: remove whitespace below footer

---

lms/static/sass/xblocks/poll_survey.scss
lms/static/sass/xblocks/problem_builder.scss

Jira Ticket: [https://edx-wiki.atlassian.net/browse/MCKIN-11597](https://edx-wiki.atlassian.net/browse/MCKIN-11597)

MCKIN-11597 - Increasing font size for poll choices

---

lms/static/sass/discussion/inline-discussion.scss
lms/static/sass/discussion/lms-discussion-bootstrap.scss

hiding discussion post title on mobile view and setting padding.

MEI-9959 hiding discussion post title on mobile view and setting padding.
